package com.bu.forum;

/**
 * @author Greg Mitten (i7676925)
 * gregoryamitten@gmail.com
 */
public enum ForumType {
    MAN_CITY_BLUE_MOON_MCFC, CHELSEA_TALK_CHELSEA, LIVERPOOL_RED_AND_WHITE, ARSENAL_ARSENAL_MANIA, CRYSTAL_PALACE_CPFC, LEICESTER_CITY_FOXES_TALK,
    EVERTON_GRAND_OLD_TEAM, BOURNEMOUTH_BOURNEMOUTH_FORUM, BURNLEY_FOOTY_MAD, LIVERPOOL_LFC_REDS, MANCHESTER_UNITED_RED_CAFE, TOTTENHAM_HOTSPURS_SPURS_COMMUNITY,
    NEWCASTLE_TOONTASTIC, WEST_BROMICH_ALBION_WEST_BROM, WEST_HAM_WEST_HAM_ONLINE, STOKE_CITY_OAKCAKE_FANZINE, CRYSTAL_PALACE_HOLMES_DALES, SOUTHAMPTON_SAINTS_WEBB,
    WATFORD_WFC_FORUMS, SWANSEA_CITY_FANS_NETWORK, ARSENAL_GOONERS_WORLD
}
