package com.bu.forum;

/**
 * @author Greg Mitten (i7676925)
 * gregoryamitten@gmail.com
 */
public enum ForumType {
    MAN_CITY_BLUE_MOON_MCFC, CHELSEA_TALK_CHELSEA, LIVERPOOL_RED_AND_WHITE, ARSENAL_ARSENAL_MANIA, CRYSTAL_PALACE_CPFC, LEICESTER_CITY_FOXES_TALK,
    EVERTON_GRAND_OLD_TEAM, BOURNEMOUTH_BOURNEMOUTH_FORUM
}
